### PR TITLE
Feature development

### PR DESCRIPTION
**Pull request by Coco-hanqi**
Features can be get from the get_feature() function in app.py

### CODE REVIEW

**Review by sidbansal00 — COMMENTED** [review]
I'm not sure what get_feature does. The features array that we are building onto, we can just call the model with that since the flask server is running Python.

**Comment by Coco-hanqi** [comment]
> I'm not sure what get_feature does. The features array that we are building onto, we can just call the model with that since the flask server is running Python.

get_feature only cleans the keypoint data, which we get from javascript, and make the json object into the pandas dataframe that can be directly feed into the model.

**Comment by Coco-hanqi** [comment]
> I'm not sure what get_feature does. The features array that we are building onto, we can just call the model with that since the flask server is running Python.

Does the above explanation make sense?

**Comment by sidbansal00** [comment]
> > I'm not sure what get_feature does. The features array that we are building onto, we can just call the model with that since the flask server is running Python.
> 
> Does the above explanation make sense?

Yup got it! So we still need some logic that will know when to call get_feature and call the model with the dataframe right?

**Comment by Coco-hanqi** [comment]
> > > I'm not sure what get_feature does. The features array that we are building onto, we can just call the model with that since the flask server is running Python.
> > 
> > 
> > Does the above explanation make sense?
> 
> Yup got it! So we still need some logic that will know when to call get_feature and call the model with the dataframe right?

Yah. I think Rohan deals with that part in his logic_handler code?

**Review by TuckerCullen — COMMENTED** [review]
I think this looks good to merge to main, except I think some of the extracted feature data itself got pushed in the last commit? It is too big to pull now. So we might want to add that to the .gitignore

**Pull request closed without merging**
